/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSolicitarRouteImport } from './routes/_authenticated/solicitar'
import { Route as AuthenticatedMisRecibosRouteImport } from './routes/_authenticated/mis-recibos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminProgramasRouteImport } from './routes/_authenticated/admin.programas'
import { Route as AuthenticatedAdminPlantillasRouteImport } from './routes/_authenticated/admin.plantillas'
import { Route as AuthenticatedAdminNumeracionRouteImport } from './routes/_authenticated/admin.numeracion'
import { Route as AuthenticatedAdminFormularioRouteImport } from './routes/_authenticated/admin.formulario'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminPlantillasIdEditorRouteImport } from './routes/_authenticated/admin.plantillas.$id.editor'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSolicitarRoute = AuthenticatedSolicitarRouteImport.update({
  id: '/solicitar',
  path: '/solicitar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMisRecibosRoute = AuthenticatedMisRecibosRouteImport.update({
  id: '/mis-recibos',
  path: '/mis-recibos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProgramasRoute =
  AuthenticatedAdminProgramasRouteImport.update({
    id: '/programas',
    path: '/programas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlantillasRoute =
  AuthenticatedAdminPlantillasRouteImport.update({
    id: '/plantillas',
    path: '/plantillas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNumeracionRoute =
  AuthenticatedAdminNumeracionRouteImport.update({
    id: '/numeracion',
    path: '/numeracion',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFormularioRoute =
  AuthenticatedAdminFormularioRouteImport.update({
    id: '/formulario',
    path: '/formulario',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlantillasIdEditorRoute =
  AuthenticatedAdminPlantillasIdEditorRouteImport.update({
    id: '/$id/editor',
    path: '/$id/editor',
    getParentRoute: () => AuthenticatedAdminPlantillasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/mis-recibos': typeof AuthenticatedMisRecibosRoute
  '/solicitar': typeof AuthenticatedSolicitarRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/formulario': typeof AuthenticatedAdminFormularioRoute
  '/admin/numeracion': typeof AuthenticatedAdminNumeracionRoute
  '/admin/plantillas': typeof AuthenticatedAdminPlantillasRouteWithChildren
  '/admin/programas': typeof AuthenticatedAdminProgramasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/plantillas/$id/editor': typeof AuthenticatedAdminPlantillasIdEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mis-recibos': typeof AuthenticatedMisRecibosRoute
  '/solicitar': typeof AuthenticatedSolicitarRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/formulario': typeof AuthenticatedAdminFormularioRoute
  '/admin/numeracion': typeof AuthenticatedAdminNumeracionRoute
  '/admin/plantillas': typeof AuthenticatedAdminPlantillasRouteWithChildren
  '/admin/programas': typeof AuthenticatedAdminProgramasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/plantillas/$id/editor': typeof AuthenticatedAdminPlantillasIdEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/mis-recibos': typeof AuthenticatedMisRecibosRoute
  '/_authenticated/solicitar': typeof AuthenticatedSolicitarRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/formulario': typeof AuthenticatedAdminFormularioRoute
  '/_authenticated/admin/numeracion': typeof AuthenticatedAdminNumeracionRoute
  '/_authenticated/admin/plantillas': typeof AuthenticatedAdminPlantillasRouteWithChildren
  '/_authenticated/admin/programas': typeof AuthenticatedAdminProgramasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/plantillas/$id/editor': typeof AuthenticatedAdminPlantillasIdEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/mis-recibos'
    | '/solicitar'
    | '/admin/dashboard'
    | '/admin/formulario'
    | '/admin/numeracion'
    | '/admin/plantillas'
    | '/admin/programas'
    | '/admin/usuarios'
    | '/admin/'
    | '/admin/plantillas/$id/editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mis-recibos'
    | '/solicitar'
    | '/admin/dashboard'
    | '/admin/formulario'
    | '/admin/numeracion'
    | '/admin/plantillas'
    | '/admin/programas'
    | '/admin/usuarios'
    | '/admin'
    | '/admin/plantillas/$id/editor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/mis-recibos'
    | '/_authenticated/solicitar'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/formulario'
    | '/_authenticated/admin/numeracion'
    | '/_authenticated/admin/plantillas'
    | '/_authenticated/admin/programas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/plantillas/$id/editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/solicitar': {
      id: '/_authenticated/solicitar'
      path: '/solicitar'
      fullPath: '/solicitar'
      preLoaderRoute: typeof AuthenticatedSolicitarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mis-recibos': {
      id: '/_authenticated/mis-recibos'
      path: '/mis-recibos'
      fullPath: '/mis-recibos'
      preLoaderRoute: typeof AuthenticatedMisRecibosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/programas': {
      id: '/_authenticated/admin/programas'
      path: '/programas'
      fullPath: '/admin/programas'
      preLoaderRoute: typeof AuthenticatedAdminProgramasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plantillas': {
      id: '/_authenticated/admin/plantillas'
      path: '/plantillas'
      fullPath: '/admin/plantillas'
      preLoaderRoute: typeof AuthenticatedAdminPlantillasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/numeracion': {
      id: '/_authenticated/admin/numeracion'
      path: '/numeracion'
      fullPath: '/admin/numeracion'
      preLoaderRoute: typeof AuthenticatedAdminNumeracionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/formulario': {
      id: '/_authenticated/admin/formulario'
      path: '/formulario'
      fullPath: '/admin/formulario'
      preLoaderRoute: typeof AuthenticatedAdminFormularioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plantillas/$id/editor': {
      id: '/_authenticated/admin/plantillas/$id/editor'
      path: '/$id/editor'
      fullPath: '/admin/plantillas/$id/editor'
      preLoaderRoute: typeof AuthenticatedAdminPlantillasIdEditorRouteImport
      parentRoute: typeof AuthenticatedAdminPlantillasRoute
    }
  }
}

interface AuthenticatedAdminPlantillasRouteChildren {
  AuthenticatedAdminPlantillasIdEditorRoute: typeof AuthenticatedAdminPlantillasIdEditorRoute
}

const AuthenticatedAdminPlantillasRouteChildren: AuthenticatedAdminPlantillasRouteChildren =
  {
    AuthenticatedAdminPlantillasIdEditorRoute:
      AuthenticatedAdminPlantillasIdEditorRoute,
  }

const AuthenticatedAdminPlantillasRouteWithChildren =
  AuthenticatedAdminPlantillasRoute._addFileChildren(
    AuthenticatedAdminPlantillasRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminFormularioRoute: typeof AuthenticatedAdminFormularioRoute
  AuthenticatedAdminNumeracionRoute: typeof AuthenticatedAdminNumeracionRoute
  AuthenticatedAdminPlantillasRoute: typeof AuthenticatedAdminPlantillasRouteWithChildren
  AuthenticatedAdminProgramasRoute: typeof AuthenticatedAdminProgramasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminFormularioRoute: AuthenticatedAdminFormularioRoute,
  AuthenticatedAdminNumeracionRoute: AuthenticatedAdminNumeracionRoute,
  AuthenticatedAdminPlantillasRoute:
    AuthenticatedAdminPlantillasRouteWithChildren,
  AuthenticatedAdminProgramasRoute: AuthenticatedAdminProgramasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMisRecibosRoute: typeof AuthenticatedMisRecibosRoute
  AuthenticatedSolicitarRoute: typeof AuthenticatedSolicitarRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMisRecibosRoute: AuthenticatedMisRecibosRoute,
  AuthenticatedSolicitarRoute: AuthenticatedSolicitarRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
